# -*- coding: utf-8 -*-
"""Burslu Master / PhD Program Bulucu - ulke/burs/fon veri tabani (app.py ve calendar_export.py tarafindan paylasilir)."""

COUNTRIES = ["Almanya", "Hollanda", "İsviçre", "İtalya", "İspanya"]

# Küratörlü veri tabanı: burs/fon sağlayan program ve kaynaklar.
# funding: "Tam Burs", "Maaşlı Kadro", "Burs (kısmi/değişken)"
PROGRAMS = [
    # ---------------- ALMANYA ----------------
    {
        "name": "DAAD EPOS / Development-Related Postgraduate Courses",
        "country": "Almanya",
        "degree": "Master",
        "field": "Sosyal Bilimler / Eğitim",
        "funding": "Tam Burs",
        "sponsor_note": "Doğrulandı (2026): yüksek lisans için aylık 992 €, doktora için 1.300 € (Şubat 2026'dan itibaren 1.400 €); sağlık/kaza/sorumluluk sigortası + yol ücreti dahil. Başvuru doğrudan ilgili programa yapılır, DAAD'a değil.",
        "fit": "ELT + eğitim bilimleri profiline çok uygun; iş deneyimi şartı olan programlar var.",
        "url": "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50076777",
        "deadline_hint": "Programa göre Ağustos–Ekim arası",
    },
    {
        "name": "DAAD Research Grants – Doctoral Programmes in Germany",
        "country": "Almanya",
        "degree": "PhD",
        "field": "Tüm Alanlar (Sosyal Bilimler dahil)",
        "funding": "Tam Burs",
        "sponsor_note": "Aylık ~1.300 €, sigorta, aile ödeneği; vize sürecinde DAAD desteği.",
        "fit": "Tez aşamasındaki yüksek lisans öğrencileri başvurabilir; Almanya'da danışman kabulü gerekir.",
        "url": "https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/",
        "deadline_hint": "Genellikle yıllık, sonbahar",
    },
    {
        "name": "Universität Hamburg – Doctoral Programme Language Sciences (IGDK vb.)",
        "country": "Almanya",
        "degree": "PhD",
        "field": "Uygulamalı Dilbilim / Dil Eğitimi",
        "funding": "Maaşlı Kadro",
        "fit": "ELT tezinle doğrudan örtüşür; wissenschaftliche/r Mitarbeiter/in kadroları maaşlıdır (TV-L E13 %50-65).",
        "sponsor_note": "İş sözleşmesi = oturum izni sponsorluğu; Almanya'da doktora çoğunlukla maaşlı kadroyla yapılır.",
        "url": "https://www.uni-hamburg.de/en/forschung/nachwuchs/promotion.html",
        "deadline_hint": "Kadro ilanına göre değişir",
    },
    {
        "name": "Max Planck / IMPRS Doctoral Positions (ör. IMPRS LSD – Psycholinguistics, Nijmegen-Berlin ağı)",
        "country": "Almanya",
        "degree": "PhD",
        "field": "Dilbilim / Bilişsel Bilim",
        "funding": "Maaşlı Kadro",
        "fit": "Dil edinimi/öğretimi araştırması yapan ELT mezunları için güçlü seçenek.",
        "sponsor_note": "Doğrulandı (2026): IMPRS for Language Sciences (Nijmegen/MPI for Psycholinguistics) 2026–2030 kohortu için aylık brüt ~3.185,72 € (+ %8 tatil ikramiyesi, yıllık ~41.287 €), 4 yıl tam fonlu, Eylül/Ekim 2026 başlangıç. Tam maaşlı sözleşme, vize desteği kurum tarafından verilir.",
        "url": "https://www.mpg.de/en/imprs",
        "deadline_hint": "Yıl boyu ilan bazlı; IMPRS LSD kohortu için başvuru genelde kış aylarında",
    },
    {
        "name": "Konrad-Adenauer / Friedrich-Ebert / Heinrich-Böll Vakıf Bursları",
        "country": "Almanya",
        "degree": "Master + PhD",
        "field": "Sosyal Bilimler",
        "funding": "Tam Burs",
        "fit": "Uluslararası öğrencilere açık siyasi vakıf bursları; sosyal katılım/aktivizm geçmişi avantaj.",
        "sponsor_note": "Aylık burs + sigorta; öğrenci vizesi için yeterli finansman belgesi sağlar.",
        "url": "https://www.study-in-germany.de/en/plan-your-studies/requirements/costs-scholarships/scholarships/",
        "deadline_hint": "Vakfa göre yılda 1–2 dönem",
    },
    # ---------------- HOLLANDA ----------------
    {
        "name": "PhD Positions in the Netherlands (Employed PhD – tüm üniversiteler)",
        "country": "Hollanda",
        "degree": "PhD",
        "field": "Tüm Alanlar (Eğitim/Dilbilim dahil)",
        "funding": "Maaşlı Kadro",
        "fit": "Hollanda'da PhD bir iştir: doğrulanan örnekler (Leiden Dilbilim Merkezi) 1. yıl ~3.059 €'dan 4. yıl ~3.881 €'ya çıkan brüt maaş + ikramiyeler, 4 yıl sözleşme. ELT/uygulamalı dilbilim ilanları düzenli çıkar.",
        "sponsor_note": "Üniversite 'recognised sponsor' olarak highly skilled migrant vizesi çıkarır — sponsorluk garantidir.",
        "url": "https://www.academictransfer.com/en/jobs/?q=applied+linguistics",
        "deadline_hint": "Sürekli ilan bazlı",
    },
    {
        "name": "University of Groningen – Center for Language and Cognition (CLCG) PhD",
        "country": "Hollanda",
        "degree": "PhD",
        "field": "Uygulamalı Dilbilim / Dil Öğretimi",
        "funding": "Maaşlı Kadro",
        "fit": "İkinci dil edinimi ve dil öğretimi araştırma grubu güçlü; ELT teziyle doğrudan bağlantı.",
        "sponsor_note": "Maaşlı pozisyon + vize sponsorluğu.",
        "url": "https://www.rug.nl/research/clcg/",
        "deadline_hint": "İlan bazlı",
    },
    {
        "name": "Leiden University Excellence Scholarship (LExS)",
        "country": "Hollanda",
        "degree": "Master",
        "field": "Sosyal Bilimler",
        "funding": "Burs (kısmi/değişken)",
        "fit": "Doğrulandı (2026): Yılda ~25 kişilik kontenjana 1000+ başvuru var — çok rekabetçi; tutar 10.000 €, 15.000 € veya tam harç eksi zorunlu harç kademelerinde. GPA 3.44 rekabetçi sınırda ama başvurulabilir.",
        "sponsor_note": "Burs belgesi vize finansman şartını karşılar.",
        "url": "https://www.universiteitleiden.nl/en/scholarships/sea/leiden-university-excellence-scholarship-lexs",
        "deadline_hint": "Eylül girişi için 1 Şubat, Şubat girişi için 1 Ekim",
    },
    {
        "name": "Radboud Scholarship Programme",
        "country": "Hollanda",
        "degree": "Master",
        "field": "Sosyal Bilimler",
        "funding": "Burs (kısmi/değişken)",
        "fit": "Doğrulandı (2026-27): Faculty of Arts (4) ve Faculty of Social Sciences (8) dahil toplam 33 kontenjan; harcı ~2.695 €'ya düşürüyor + vize/oturum izni/sigorta masraflarını karşılıyor (tam burs değil, kısmi).",
        "sponsor_note": "Not: Utrecht Excellence Scholarship (UES) bütçe kesintisi nedeniyle 2026–2027 girişinden itibaren tamamen kaldırıldı — artık başvuruya açık değil.",
        "url": "https://www.ru.nl/en/education/scholarships/radboud-scholarship-programme",
        "deadline_hint": "2026-27 girişi için son başvuru geçti (31 Ocak); bir sonraki döngü de genelde Ocak sonu",
    },
    # ---------------- İSVİÇRE ----------------
    {
        "name": "Swiss Government Excellence Scholarships",
        "country": "İsviçre",
        "degree": "PhD",
        "field": "Tüm Alanlar",
        "funding": "Tam Burs",
        "fit": "Türkiye kotası var; aylık ~1.920 CHF, sigorta, harç muafiyeti. Sosyal bilimler başvuruları kabul edilir.",
        "sponsor_note": "Devlet bursu — vize/oturum süreci resmi olarak desteklenir. Not: 2026-2027 döngüsü için ülke bazlı son başvuru tarihleri Ağustos 2026'da yayınlanacak (başvurular 20 Ağustos 2026'da açılıyor); doğum tarihi şartı: 31 Aralık 1990'dan sonra.",
        "url": "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
        "deadline_hint": "Geçmiş yıllarda Türkiye için genellikle Kasım–Aralık; 2026-27 için resmi tarih Ağustos 2026'da netleşecek",
    },
    {
        "name": "University of Zurich / Bern / Geneva – Doctoral Positions (Assistant kadroları)",
        "country": "İsviçre",
        "degree": "PhD",
        "field": "Eğitim Bilimleri / Dilbilim",
        "funding": "Maaşlı Kadro",
        "fit": "Doktora asistanlığı maaşları yüksek (~47.000–50.000 CHF/yıl); English linguistics bölümleri ELT geçmişini kabul eder.",
        "sponsor_note": "İş sözleşmesiyle oturum izni alınır.",
        "url": "https://www.jobs.uzh.ch/",
        "deadline_hint": "İlan bazlı",
    },
    # ---------------- İTALYA ----------------
    {
        "name": "İtalya Devlet PhD Bursları (tüm devlet üniversiteleri, 'borsa di dottorato')",
        "country": "İtalya",
        "degree": "PhD",
        "field": "Sosyal Bilimler / Dilbilim / Eğitim",
        "funding": "Tam Burs",
        "fit": "İtalya'da PhD kontenjanlarının çoğu burslu; yabancı adaylara ek kontenjan ayıran çağrılar var. GPA baraj değil, proje önemli.",
        "sponsor_note": "Doğrulandı (42. döngü, 2026-27): brüt yıllık burs 18.345 €–25.200 € arası (üniversiteye göre değişir); uygun yabancı adaylara ek olarak tek seferlik ~5.000 €'ya kadar yerleşim desteği de verilebiliyor. Burs belgesi ile öğrenci oturum izni (permesso di soggiorno) alınır.",
        "url": "https://www.universitaly.it/",
        "deadline_hint": "Çağrılar Mayıs–Temmuz (36. döngü tarzı yıllık)",
    },
    {
        "name": "Ca' Foscari Venedik / Bologna / Padova – Language Sciences PhD",
        "country": "İtalya",
        "degree": "PhD",
        "field": "Dil Bilimleri / Dil Eğitimi",
        "funding": "Tam Burs",
        "fit": "Ca' Foscari'nin 'Language Sciences' doktorası dil öğretimi araştırmasını kapsar — ELT profili için birebir.",
        "sponsor_note": "Burslu kontenjan + üniversitenin vize destek ofisi.",
        "url": "https://www.unive.it/pag/7987/",
        "deadline_hint": "Genellikle Mayıs–Haziran",
    },
    {
        "name": "İtalya Hükümeti (MAECI) Yabancı Öğrenci Bursları",
        "country": "İtalya",
        "degree": "Master",
        "field": "Tüm Alanlar",
        "funding": "Tam Burs",
        "fit": "Türkiye vatandaşlarına açık; aylık ~900 €, harç muafiyeti, sigorta.",
        "sponsor_note": "Devlet bursu vize sürecini kolaylaştırır.",
        "url": "https://studyinitaly.esteri.it/en/call-for-procedure",
        "deadline_hint": "Genellikle ilkbahar",
    },
    # ---------------- İSPANYA ----------------
    {
        "name": "'la Caixa' Foundation Doctoral INPhINIT Fellowships",
        "country": "İspanya",
        "degree": "PhD",
        "field": "Tüm Alanlar (Retaining ayağı sosyal bilimleri kapsar)",
        "funding": "Tam Burs",
        "fit": "3 yıl, yıllık ~35.800 € — Avrupa'nın en iyi doktora burslarından; rekabetçi ama sosyal bilimlere açık.",
        "sponsor_note": "Doğrulandı (2026 döngüsü): 'Incoming' çağrısı 28 Ocak 2026, 'Retaining' çağrısı 18 Şubat 2026'da kapandı; her iki program da tüm uyruklara açık ve doktora sözleşmesi 4 yıla kadar iş maliyeti + araştırma + harç kapsıyor. Tam fonlu sözleşme, vize desteği.",
        "url": "https://lacaixafoundation.org/en/doctoral-inphinit-fellowships",
        "deadline_hint": "Yıllık: Incoming çağrı ~Ocak sonu, Retaining çağrı ~Şubat ortası",
    },
    {
        "name": "FPI / FPU – İspanya Devlet Doktora Sözleşmeleri",
        "country": "İspanya",
        "degree": "PhD",
        "field": "Tüm Alanlar",
        "funding": "Maaşlı Kadro",
        "fit": "Devlet destekli 4 yıllık doktora sözleşmeleri; uygulamalı dilbilim/eğitim projelerine bağlı pozisyonlar çıkar.",
        "sponsor_note": "İş sözleşmesi ile oturum izni.",
        "url": "https://www.aei.gob.es/",
        "deadline_hint": "Yıllık çağrı (sonbahar/kış)",
    },
    {
        "name": "Erasmus Mundus Joint Masters (ör. dil eğitimi/çok dillilik programları)",
        "country": "İspanya",
        "degree": "Master",
        "field": "Dil Eğitimi / Sosyal Bilimler",
        "funding": "Tam Burs",
        "fit": "AB dışı adaylara tam burs (aylık ~1.000–1.400 € + harç + yol/sigorta). Birden fazla AB ülkesinde okutur; İspanya-İtalya-Almanya ortaklı programlar mevcut.",
        "sponsor_note": "Erasmus Mundus bursu vize sürecinde resmi sponsorluk sağlar.",
        "url": "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
        "deadline_hint": "Genellikle Aralık–Şubat",
    },
    {
        "name": "TELME – Erasmus Mundus Joint Master (Teaching Foreign Languages in Multicultural Environments)",
        "country": "İspanya",
        "degree": "Master",
        "field": "Dil Eğitimi / Uygulamalı Dilbilim",
        "funding": "Tam Burs",
        "fit": "Yeni onaylanan (2026 kataloğu) EMJM programı; konsorsiyum: Université Rennes 2 (koordinatör, Fransa), Åbo Akademi (Finlandiya), Universidad de Burgos (İspanya), University of Limerick (İrlanda), Adam Mickiewicz University (Polonya). ELT geçmişi ve çok dilli/kültürlü sınıf yönetimi odağıyla birebir örtüşüyor; İngilizce + Fransızca/İspanyolca/Almanca bilgisi isteniyor.",
        "sponsor_note": "İlk kohort için ~30 öğrenciye AB bursu: harç + yol + yaşam masrafı tam karşılanıyor. Eylül 2026'da başlıyor.",
        "url": "https://telme.hypotheses.org/",
        "deadline_hint": "İlk çağrı 20 Ocak 2026'da kapandı; sonraki yıllar için benzer takvim (Ocak ortası) beklenir",
    },
]

SEARCH_PORTALS = [
    ("FindAPhD", "https://www.findaphd.com/phds/?Keywords={q}"),
    ("EURAXESS (AB resmi ilan portalı)", "https://euraxess.ec.europa.eu/jobs/search?keywords={q}"),
    ("Academic Positions", "https://academicpositions.com/find-jobs?search={q}"),
    ("ScholarshipDb", "https://scholarshipdb.net/scholarships?q={q}"),
    ("DAAD Burs Veritabanı", "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/"),
    ("AcademicTransfer (Hollanda)", "https://www.academictransfer.com/en/jobs/?q={q}"),
]
