# -*- coding: utf-8 -*-
"""Burslu Master / PhD Program Bulucu - ulke/burs/fon veri tabani (app.py ve calendar_export.py tarafindan paylasilir)."""

COUNTRIES = ["Almanya", "Hollanda", "İsviçre", "İtalya", "İspanya"]

# Küratörlü veri tabanı: burs/fon sağlayan program ve kaynaklar.
# funding: "Tam Burs", "Maaşlı Kadro", "Burs (kısmi/değişken)"
# requirements: başvuru için fiilen gereken belgeler/adımlar (resmi sayfa + FAQ/PDF taramasından çıkarıldı)
PROGRAMS = [
    # ---------------- ALMANYA ----------------
    {
        "name": "DAAD EPOS / Development-Related Postgraduate Courses",
        "country": "Almanya",
        "degree": "Master",
        "field": "Sosyal Bilimler / Eğitim",
        "funding": "Tam Burs",
        "sponsor_note": "Doğrulandı (2026): yüksek lisans için aylık 992 €, doktora için 1.300 € (Şubat 2026'dan itibaren 1.400 €); sağlık/kaza/sorumluluk sigortası + yol ücreti dahil. Başvuru doğrudan ilgili programa yapılır, DAAD'a değil.",
        "fit": "ELT + eğitim bilimleri profiline çok uygun; iş deneyimi şartı olan programlar var.",
        "requirements": [
            "CV (Europass formatında, kronolojik, boşluksuz)",
            "Motivasyon mektubu (en fazla 3 program seçilebilir, tek mektupta öncelik sırası açıklanır)",
            "Referans mektubu (üniversite/işveren antetli kağıdı + imza + mühür)",
            "Lisans/yüksek lisans diploma + not döküm (transkript) fotokopileri",
            "Dil yeterlilik belgesi (programın eğitim dili için)",
            "İmzalı kontrol listesi (checklist) formu",
            "Not: Başvuru DAAD'a değil doğrudan ilgili programa yapılır; kabul edilirsen belgeler DAAD portalına PDF olarak yüklenir",
        ],
        "url": "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50076777",
        "deadline_hint": "Programa göre Ağustos–Ekim arası",
    },
    {
        "name": "DAAD Research Grants – Doctoral Programmes in Germany",
        "country": "Almanya",
        "degree": "PhD",
        "field": "Tüm Alanlar (Sosyal Bilimler dahil)",
        "funding": "Tam Burs",
        "sponsor_note": "Aylık ~1.300 €, sigorta, aile ödeneği; vize sürecinde DAAD desteği.",
        "fit": "Tez aşamasındaki yüksek lisans öğrencileri başvurabilir; Almanya'da danışman kabulü gerekir.",
        "requirements": [
            "Almanya'da bir danışman/enstitüden ön kabul mektubu (Betreuerzusage) — başvurudan ÖNCE temin edilmeli",
            "Doktora araştırma önerisi (genelde 4-8 sayfa)",
            "CV + yayın listesi (varsa)",
            "2 akademik referans mektubu",
            "Lisans/yüksek lisans transkript ve diplomaları",
            "Almanca veya İngilizce dil yeterlilik belgesi (programa göre)",
            "Motivasyon mektubu",
        ],
        "url": "https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/",
        "deadline_hint": "Genellikle yıllık, sonbahar",
    },
    {
        "name": "Universität Hamburg – Doctoral Programme Language Sciences (IGDK vb.)",
        "country": "Almanya",
        "degree": "PhD",
        "field": "Uygulamalı Dilbilim / Dil Eğitimi",
        "funding": "Maaşlı Kadro",
        "fit": "ELT tezinle doğrudan örtüşür; wissenschaftliche/r Mitarbeiter/in kadroları maaşlıdır (TV-L E13 %50-65).",
        "sponsor_note": "İş sözleşmesi = oturum izni sponsorluğu; Almanya'da doktora çoğunlukla maaşlı kadroyla yapılır.",
        "requirements": [
            "Bu bir iş ilanıdır — ilana özel CV + kapak mektubu (cover letter)",
            "İlan edilen proje/pozisyonla somut uyum gösteren kısa araştırma fikri",
            "Transkript ve diploma (yüksek lisans)",
            "2 referans kişisinin iletişim bilgisi (bazı ilanlarda tam mektup istenir)",
            "Başvuru üniversitenin kendi iş/kariyer portalı üzerinden yapılır — ilan kapanmadan önce takip etmek gerekir",
        ],
        "url": "https://www.uni-hamburg.de/en/forschung/nachwuchs/promotion.html",
        "deadline_hint": "Kadro ilanına göre değişir",
    },
    {
        "name": "Max Planck / IMPRS Doctoral Positions (ör. IMPRS Language Sciences, Nijmegen)",
        "country": "Almanya",
        "degree": "PhD",
        "field": "Dilbilim / Bilişsel Bilim",
        "funding": "Maaşlı Kadro",
        "fit": "Dil edinimi/öğretimi araştırması yapan ELT mezunları için güçlü seçenek.",
        "sponsor_note": "ÖNEMLİ GÜNCELLEME (doğrulandı): IMPRS for Language Sciences'ın yıllık 'IMPRS Fellowships' çağrısı tamamen KALDIRILDI, yeni tur açılmayacak. Bunun yerine enstitünün 'Vacancies' (kadro ilanları) sayfasından tek tek çıkan PhD pozisyonlarını takip etmek gerekiyor — bunlar hâlâ aktif ve maaşlı (TV-L bazlı, ~3.000-3.400 €/ay brüt bandı).",
        "requirements": [
            "Enstitünün kendi CV ve motivasyon mektubu şablonlarını kullanmak zorunlu (genel şablon değil)",
            "Motivasyon mektubu max 750 kelime; hangi ilan/temaya başvurulduğu üstte belirtilmeli",
            "Diploma + transkript (İngilizce/Almanca/Hollandaca değilse çeviri şart)",
            "Tam referans mektubu değil, 3 referans kişisinin isim+e-posta bilgisi (mülakata çağrılırsa mektup istenir)",
            "Güncel açık pozisyonlar için 'Vacancies' sayfasını düzenli kontrol et — yıllık tek bir başvuru penceresi artık yok",
        ],
        "url": "https://www.mpi.nl/department/imprs-graduate-school/13/vacancies",
        "deadline_hint": "Sabit tarih yok — kadro ilanı çıktıkça, yıl boyu",
    },
    {
        "name": "Konrad-Adenauer / Friedrich-Ebert / Heinrich-Böll Vakıf Bursları",
        "country": "Almanya",
        "degree": "Master + PhD",
        "field": "Sosyal Bilimler",
        "funding": "Tam Burs",
        "fit": "Uluslararası öğrencilere açık siyasi vakıf bursları; sosyal katılım/aktivizm geçmişi avantaj.",
        "sponsor_note": "Doğrulandı: Her üç vakıf da güçlü akademik not + somut sosyal/politik katılım (gönüllülük, sivil toplum, demokrasi/insan hakları duyarlılığı) arıyor; Almanca B2 şartı genelde var (vakfa göre değişir).",
        "requirements": [
            "Tablo formatında CV — gönüllü çalışma/sosyal sorumluluk deneyimleri ayrıca vurgulanmalı",
            "Almanca B2 seviyesi dil sertifikası (çoğu vakıf için zorunlu)",
            "Sosyal/politik katılımı anlatan ayrı bir motivasyon/deneyim yazısı (vakfın değerleriyle örtüşüm önemli: KAS-muhafazakar/Hristiyan demokrat, FES-sosyal demokrat, Böll-yeşil/ekoloji)",
            "Almanya'daki bir üniversiteye kabul veya kabul başvurusu kanıtı",
            "2 referans mektubu",
            "Transkript ve diploma",
        ],
        "url": "https://www.study-in-germany.de/en/plan-your-studies/requirements/costs-scholarships/scholarships/",
        "deadline_hint": "Vakfa göre yılda 1–2 dönem",
    },
    # ---------------- HOLLANDA ----------------
    {
        "name": "PhD Positions in the Netherlands (Employed PhD – tüm üniversiteler)",
        "country": "Hollanda",
        "degree": "PhD",
        "field": "Tüm Alanlar (Eğitim/Dilbilim dahil)",
        "funding": "Maaşlı Kadro",
        "fit": "Hollanda'da PhD bir iştir: doğrulanan örnekler (Leiden Dilbilim Merkezi) 1. yıl ~3.059 €'dan 4. yıl ~3.881 €'ya çıkan brüt maaş + ikramiyeler, 4 yıl sözleşme. ELT/uygulamalı dilbilim ilanları düzenli çıkar.",
        "sponsor_note": "Üniversite 'recognised sponsor' olarak highly skilled migrant vizesi çıkarır — sponsorluk garantidir.",
        "requirements": [
            "Kapak mektubu / motivasyon mektubu (Hollanda'da 'cover letter' ve 'motivation letter' eşanlamlı kullanılır, max 1-2 sayfa)",
            "Akademik CV (araştırma deneyimi + varsa yayın listesi ayrı bölüm)",
            "İlan edilen projeyle somut uyum gösteren kısa bir niyet/fikir paragrafı",
            "2-3 akademik referansın iletişim bilgisi",
            "Diploma + transkript",
            "Not: rekabet çok yüksek (bazı ilanlara 100-200 başvuru); somut proje uyumu ve yayın/araştırma deneyimi belirleyici",
        ],
        "url": "https://www.academictransfer.com/en/jobs/?q=applied+linguistics",
        "deadline_hint": "Sürekli ilan bazlı",
    },
    {
        "name": "University of Groningen – Center for Language and Cognition (CLCG) PhD",
        "country": "Hollanda",
        "degree": "PhD",
        "field": "Uygulamalı Dilbilim / Dil Öğretimi",
        "funding": "Maaşlı Kadro",
        "fit": "İkinci dil edinimi ve dil öğretimi araştırma grubu güçlü; ELT teziyle doğrudan bağlantı.",
        "sponsor_note": "Maaşlı pozisyon + vize sponsorluğu.",
        "requirements": [
            "İlan bazlı kadroya CV + kapak mektubu",
            "Dışarıdan (harici) PhD adayları için Groningen'in ayrı 'documentation' şartları geçerli olabilir (danışman ön onayı, araştırma planı) — ilan/başvuru sayfasına göre değişir",
            "Diploma + transkript",
            "2 referans kişisi",
        ],
        "url": "https://www.rug.nl/research/clcg/",
        "deadline_hint": "İlan bazlı",
    },
    {
        "name": "Leiden University Excellence Scholarship (LExS)",
        "country": "Hollanda",
        "degree": "Master",
        "field": "Sosyal Bilimler",
        "funding": "Burs (kısmi/değişken)",
        "fit": "Doğrulandı (2026): Yılda ~25 kişilik kontenjana 1000+ başvuru var — çok rekabetçi; tutar 10.000 €, 15.000 € veya tam harç eksi zorunlu harç kademelerinde. GPA 3.44 rekabetçi sınırda ama başvurulabilir.",
        "sponsor_note": "Burs belgesi vize finansman şartını karşılar.",
        "requirements": [
            "Önce programa KOŞULSUZ kabul almış olmak şart — burs ayrı başvurulmuyor, program başvurusu sırasında otomatik değerlendiriliyor",
            "Studielink + üniversitenin başvuru sistemi üzerinden standart master başvuru evrakları (transkript, diploma, motivasyon mektubu, CV, referans)",
            "Ayrı bir burs denemesi/essay istenmiyor ama motivasyon mektubunun güçlü olması burs değerlendirmesini de etkiliyor",
        ],
        "url": "https://www.universiteitleiden.nl/en/scholarships/sea/leiden-university-excellence-scholarship-lexs",
        "deadline_hint": "Eylül girişi için 1 Şubat, Şubat girişi için 1 Ekim",
    },
    {
        "name": "Radboud Scholarship Programme",
        "country": "Hollanda",
        "degree": "Master",
        "field": "Sosyal Bilimler",
        "funding": "Burs (kısmi/değişken)",
        "fit": "Doğrulandı (2026-27): Faculty of Arts (4) ve Faculty of Social Sciences (8) dahil toplam 33 kontenjan; harcı ~2.695 €'ya düşürüyor + vize/oturum izni/sigorta masraflarını karşılıyor (tam burs değil, kısmi).",
        "sponsor_note": "Not: Utrecht Excellence Scholarship (UES) bütçe kesintisi nedeniyle 2026–2027 girişinden itibaren tamamen kaldırıldı — artık başvuruya açık değil.",
        "requirements": [
            "OSIRIS Application sistemi üzerinden program başvurusuyla birlikte burs kutucuğu işaretlenir",
            "Transkript, diploma, motivasyon mektubu, CV, referans mektubu (standart master evrakları)",
            "Program başvurusu tamamlanmadan burs değerlendirilmiyor",
        ],
        "url": "https://www.ru.nl/en/education/scholarships/radboud-scholarship-programme",
        "deadline_hint": "2026-27 girişi için son başvuru geçti (31 Ocak); bir sonraki döngü de genelde Ocak sonu",
    },
    # ---------------- İSVİÇRE ----------------
    {
        "name": "Swiss Government Excellence Scholarships",
        "country": "İsviçre",
        "degree": "PhD",
        "field": "Tüm Alanlar",
        "funding": "Tam Burs",
        "fit": "Türkiye kotası var; aylık ~1.920 CHF, sigorta, harç muafiyeti. Sosyal bilimler başvuruları kabul edilir.",
        "sponsor_note": "Doğrulandı (2026-27 döngüsü, derinlemesine kontrol): SÜREÇ DEĞİŞTİ — artık tamamen dijital, başvuru go.eskas.ch (ESKAS portalı) üzerinden yapılıyor, eskiden olduğu gibi büyükelçiliğe fiziksel evrak teslimi YOK. Türkiye için muhatap kurum hâlâ Bern'deki İsviçre Büyükelçiliği/Ankara'daki İsviçre Büyükelçiliği ama işlem online. Ülke bazlı kesin son başvuru tarihi Ağustos 2026'da (başvurular 20 Ağustos 2026'da açılıyor) yayınlanacak — şu an tahmini 'Kasım-Aralık' bilgisi teyit edilmedi, Ağustos'ta siteyi tekrar kontrol et.",
        "requirements": [
            "İmzalı FCS başvuru formu — artık go.eskas.ch üzerinden dijital dolduruluyor",
            "Yayın/ödül dahil detaylı CV",
            "İsviçre'deki bir hoca ile ÖNCEDEN temas kurup 'host professor' onay mektubu + o hocanın kısa CV'sini almak (kritik, başvurudan önce yapılmalı)",
            "FCS araştırma önerisi formuyla max 5 sayfa, imzalı araştırma projesi",
            "Motivasyon mektubu (max 2 sayfa)",
            "2 özel referans mektubu (FCS referans formuyla)",
            "Resmi transkript + diploma (İngilizce/Fransızca/Almanca/İtalyanca değilse onaylı çeviri)",
            "Doktor onaylı sağlık raporu + 2 vesikalık fotoğraf + pasaport fotokopisi",
            "Not: fiziksel/ıslak imzalı evrak toplama artık gerekmeyebilir (portal dijitalleşti) — go.eskas.ch üzerinde hangi belgelerin dijital yükleneceği netleşince kontrol listesi kesinleşecek",
        ],
        "url": "https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships",
        "deadline_hint": "2026-27 için kesin tarih Ağustos 2026'da açıklanacak (başvurular 20 Ağustos 2026'da başlıyor); geçmiş yıllarda Türkiye genelde Kasım-Aralık'tı ama teyitli değil",
    },
    {
        "name": "University of Zurich / Bern / Geneva – Doctoral Positions (Assistant kadroları)",
        "country": "İsviçre",
        "degree": "PhD",
        "field": "Eğitim Bilimleri / Dilbilim",
        "funding": "Maaşlı Kadro",
        "fit": "Doktora asistanlığı maaşları yüksek (~47.000–50.000 CHF/yıl); English linguistics bölümleri ELT geçmişini kabul eder.",
        "sponsor_note": "İş sözleşmesiyle oturum izni alınır.",
        "requirements": [
            "İş ilanına özel CV + kapak mektubu",
            "Transkript + diploma",
            "2 referansın iletişim bilgisi (bazı ilanlarda tam mektup)",
            "Başvuru doğrudan üniversitenin iş portalı üzerinden (jobs.uzh.ch ve eşdeğerleri)",
        ],
        "url": "https://www.jobs.uzh.ch/",
        "deadline_hint": "İlan bazlı",
    },
    # ---------------- İTALYA ----------------
    {
        "name": "İtalya Devlet PhD Bursları (tüm devlet üniversiteleri, 'borsa di dottorato')",
        "country": "İtalya",
        "degree": "PhD",
        "field": "Sosyal Bilimler / Dilbilim / Eğitim",
        "funding": "Tam Burs",
        "fit": "İtalya'da PhD kontenjanlarının çoğu burslu; yabancı adaylara ek kontenjan ayıran çağrılar var. GPA baraj değil, proje önemli.",
        "sponsor_note": "Doğrulandı (42. döngü, 2026-27): brüt yıllık burs 18.345 €–25.200 € arası (üniversiteye göre değişir); uygun yabancı adaylara ek olarak tek seferlik ~5.000 €'ya kadar yerleşim desteği de verilebiliyor. Burs belgesi ile öğrenci oturum izni (permesso di soggiorno) alınır.",
        "requirements": [
            "'Bando' (çağrı metni) üniversiteye göre DEĞİŞİR — her şey (belgeler, tarih, mülakat şekli) bandoda yazar, mutlaka orijinalinden okunmalı",
            "Diploma + transkript; yurt dışı diploması için 'dichiarazione di valore' veya CIMEA/ENIC-NARIC denklik belgesi ve İtalyanca/İngilizce/Fransızca/Almanca/İspanyolca çeviri şart",
            "CV (mesleki deneyim dahil)",
            "Araştırma projesi (~2.000-3.500 kelime, çağrıdaki temayla uyumlu olmalı — genel/soyut konular elenir)",
            "Kimlik belgesi fotokopisi",
            "Mülakat: bazı üniversiteler video-konferansla, bazıları İtalya'da yüz yüze yapıyor — bandoda belirtilir",
            "Kabul sonrası: Universitaly platformuna kayıt + konsoloslukta öğrenci vizesi başvurusu",
        ],
        "url": "https://www.universitaly.it/",
        "deadline_hint": "Çağrılar Mayıs–Temmuz (42. döngü tarzı yıllık)",
    },
    {
        "name": "Ca' Foscari Venedik / Bologna / Padova – Language Sciences PhD",
        "country": "İtalya",
        "degree": "PhD",
        "field": "Dil Bilimleri / Dil Eğitimi",
        "funding": "Tam Burs",
        "fit": "Ca' Foscari'nin 'Language Sciences' doktorası dil öğretimi araştırmasını kapsar — ELT profili için birebir.",
        "sponsor_note": "Burslu kontenjan + üniversitenin vize destek ofisi.",
        "requirements": [
            "Genel İtalya devlet PhD süreciyle aynı (bkz. yukarıdaki madde) — üniversiteye özgü bando'yu kontrol et",
            "Araştırma projesi doğrudan 'Language Sciences' doktora temalarından biriyle örtüşmeli",
        ],
        "url": "https://www.unive.it/pag/7987/",
        "deadline_hint": "Genellikle Mayıs–Haziran",
    },
    {
        "name": "İtalya Hükümeti (MAECI) Yabancı Öğrenci Bursları",
        "country": "İtalya",
        "degree": "Master",
        "field": "Tüm Alanlar",
        "funding": "Tam Burs",
        "fit": "Master, doktora, üst düzey sanat/müzik eğitimi ve yoğun dil kursları dahil kapsıyor; sadece İtalya'da yüz yüze eğitim için geçerli (uzaktan program kapsam dışı).",
        "sponsor_note": "DÜZELTME (2026-27 bandosu doğrulandı): aylık tutar ~900 € değil, 1.200 € — önceki kaydım güncel değildi. 2026-27 çağrısının son başvuru tarihi 26 Mart 2026 saat 14:00 (İtalya saati) İDİ — bu döngü artık KAPANDI. Bir sonraki çağrı (2027-28) tahminen yine Mart 2026 civarı açılır; Türkiye'nin uygun ülkeler listesinde olup olmadığı her yıl 'Study in Italy' portalındaki güncel listeden teyit edilmeli (PDF bando'dan otomatik okunamadı, portalden bakılmalı).",
        "requirements": [
            "Başvuru YALNIZCA studyinitaly.esteri.it portalı üzerinden elektronik yapılıyor — başka kanal kabul edilmiyor",
            "Bir İtalyan üniversitesine ön kabul veya kabul (bazı çağrılarda başvuru sırasında şart)",
            "Transkript + diploma (yurt dışı diploması için denklik/çeviri gerekebilir)",
            "CV + motivasyon mektubu",
            "Dil yeterlilik belgesi (İtalyanca veya İngilizce, programa göre)",
            "Teknik/bando destek: assistenza.studyinitaly@esteri.it — genel soru: borsedistudio@esteri.it",
        ],
        "url": "https://studyinitaly.esteri.it/en/call-for-procedure",
        "deadline_hint": "2026-27 çağrısı 26 Mart 2026'da kapandı; sonraki çağrı tahminen Mart 2027 (portalden teyit et)",
    },
    # ---------------- İSPANYA ----------------
    {
        "name": "'la Caixa' Foundation Doctoral INPhINIT Fellowships",
        "country": "İspanya",
        "degree": "PhD",
        "field": "Tüm Alanlar (Retaining ayağı sosyal bilimleri kapsar)",
        "funding": "Tam Burs",
        "fit": "3 yıl, yıllık ~35.800 € — Avrupa'nın en iyi doktora burslarından; rekabetçi ama sosyal bilimlere açık.",
        "sponsor_note": "Doğrulandı (2026 döngüsü): 'Incoming' çağrısı 28 Ocak 2026, 'Retaining' çağrısı 18 Şubat 2026'da kapandı; her iki program da tüm uyruklara açık ve doktora sözleşmesi 4 yıla kadar iş maliyeti + araştırma + harç kapsıyor. Tam fonlu sözleşme, vize desteği.",
        "requirements": [
            "CV",
            "Statement of purpose / motivasyon yazısı (İspanya/Portekiz'de neden bu ev sahibi kurumu seçtiğini somut gerekçelendirmeli)",
            "Araştırma önerisi (değerlendirmenin %60'ı aday potansiyeli + önerinin özgünlüğüne dayanıyor)",
            "Referans mektupları (değerlendirmede %20 ağırlık; tam sayı yıllık çağrı kurallarında belirtiliyor — kontrol et)",
            "Bir İspanya/Portekiz'deki ev sahibi kurum/danışmanla ön temas önerilir",
        ],
        "url": "https://lacaixafoundation.org/en/doctoral-inphinit-fellowships",
        "deadline_hint": "Yıllık: Incoming çağrı ~Ocak sonu, Retaining çağrı ~Şubat ortası",
    },
    {
        "name": "FPI / FPU – İspanya Devlet Doktora Sözleşmeleri",
        "country": "İspanya",
        "degree": "PhD",
        "field": "Tüm Alanlar",
        "funding": "Maaşlı Kadro",
        "fit": "Devlet destekli 4 yıllık doktora sözleşmeleri; uygulamalı dilbilim/eğitim projelerine bağlı pozisyonlar çıkar.",
        "sponsor_note": "ÖNEMLİ UYARI (derinlemesine doğrulandı, 2026 döngüsü): Bu ikisi Türkiye'den DOĞRUDAN vize sponsorluğu alacağın bir yol DEĞİL — pratikte önce bir şekilde İspanya'da bir doktora programına kayıtlı/kabul edilmiş olman ve fonlanmış bir araştırma grubuna dahil olman gerekiyor; AB dışı adaylar için yabancı diploma denkliği (homologación) ve İspanyolca yeterlilik kanıtı şart, ve başvuru sırasında zaten İspanya'da yasal ikamet/öğrenci vizesi süreci genelde beklenir. Yani bunu 'ilk sponsorluk kapısı' değil, zaten bir şekilde İspanya bağlantısı kurmuş birinin ikinci aşama finansman aracı olarak gör. FPU 2026'da önemli bir kolaylaştırma oldu: artık başvuru anında doktora programına kayıtlı olma şartı kalktı (sadece sözleşme imzalanırken gerekiyor).",
        "requirements": [
            "FPI: Bakanlığın yayınladığı fonlanmış proje listesinden (kod bazlı) bir projeye başvuruluyor — bağımsız/proje dışı başvuru yok",
            "FPI belgeleri: 'Memoria del proyecto formativo' (tez + eğitim faaliyetleri planı), akademik not ortalaması dökümü, başvuru Portal del Personal Investigador üzerinden",
            "FPI 2026 başvuru penceresi: 1-30 Eylül 2026 (elektronik)",
            "FPU: değerlendirme 75 puan adayın akademik geçmişi (min eşik 60) + 25 puan ev sahibi ekibin bilimsel geçmişi; toplam yardım ~143.350 € (4 yıla yayılı)",
            "FPU 2026 başvuru penceresi: 20 Ekim - 20 Kasım 2026 (elektronik, artık AEI tarafından koordine ediliyor)",
            "AB dışı vatandaşlar için: yurt dışı diplomasının resmi denklik (homologación) belgesi + İspanyolca yeterlilik kanıtı gerekiyor",
            "CV + akademik transkript",
            "Proje ekibinin/danışmanın desteği ve başvuru formuna dahil edilmesi",
        ],
        "url": "https://www.aei.gob.es/",
        "deadline_hint": "FPI: 1-30 Eylül 2026 · FPU: 20 Ekim - 20 Kasım 2026",
    },
    {
        "name": "Erasmus Mundus Joint Masters (ör. dil eğitimi/çok dillilik programları)",
        "country": "İspanya",
        "degree": "Master",
        "field": "Dil Eğitimi / Sosyal Bilimler",
        "funding": "Tam Burs",
        "fit": "AB dışı adaylara tam burs (aylık ~1.000–1.400 € + harç + yol/sigorta). Birden fazla AB ülkesinde okutur; İspanya-İtalya-Almanya ortaklı programlar mevcut.",
        "sponsor_note": "Erasmus Mundus bursu vize sürecinde resmi sponsorluk sağlar.",
        "requirements": [
            "Lisans diploma + transkript (orijinal + onaylı çeviri, İngilizce değilse)",
            "Dil yeterlilik belgesi (genelde IELTS/TOEFL)",
            "2 (bazen 3) referans mektubu, en az 1 tanesi akademik",
            "Motivasyon mektubu (~500 kelime veya programın kendi formu)",
            "CV (format serbest)",
            "Not: her program konsorsiyumunun kendi başvuru portalı var — 'genel Erasmus Mundus başvurusu' diye tek bir yer yok, program bazlı başvurulur",
        ],
        "url": "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
        "deadline_hint": "Genellikle Aralık–Şubat",
    },
    {
        "name": "TELME – Erasmus Mundus Joint Master (Teaching Foreign Languages in Multicultural Environments)",
        "country": "İspanya",
        "degree": "Master",
        "field": "Dil Eğitimi / Uygulamalı Dilbilim",
        "funding": "Tam Burs",
        "fit": "Yeni onaylanan (2026 kataloğu) EMJM programı; konsorsiyum: Université Rennes 2 (koordinatör, Fransa), Åbo Akademi (Finlandiya), Universidad de Burgos (İspanya), University of Limerick (İrlanda), Adam Mickiewicz University (Polonya). ELT geçmişi ve çok dilli/kültürlü sınıf yönetimi odağıyla birebir örtüşüyor; İngilizce + Fransızca/İspanyolca/Almanca bilgisi isteniyor.",
        "sponsor_note": "İlk kohort için ~30 öğrenciye AB bursu: harç + yol + yaşam masrafı tam karşılanıyor. Eylül 2026'da başlıyor.",
        "requirements": [
            "İngilizce YETERLİLİK ŞART + Fransızca/İspanyolca/Almanca'dan en az birinde çalışabilir seviye isteniyor (tam eşik programın kendi sayfasında)",
            "Standart Erasmus Mundus evrakları: diploma+transkript, 2-3 referans, motivasyon mektubu, CV",
            "Başvuru telme.hypotheses.org üzerinden duyurulan konsorsiyum portalından yapılıyor",
            "İlk çağrı tek seferlikti (20 Ocak 2026) — sonraki yıllık çağrı tarihi henüz teyit edilmedi, sayfayı takip et",
        ],
        "url": "https://telme.hypotheses.org/",
        "deadline_hint": "İlk çağrı 20 Ocak 2026'da kapandı; sonraki yıllar için benzer takvim (Ocak ortası) beklenir",
    },
]

SEARCH_PORTALS = [
    ("FindAPhD", "https://www.findaphd.com/phds/?Keywords={q}"),
    ("EURAXESS (AB resmi ilan portalı)", "https://euraxess.ec.europa.eu/jobs/search?keywords={q}"),
    ("Academic Positions", "https://academicpositions.com/find-jobs?search={q}"),
    ("ScholarshipDb", "https://scholarshipdb.net/scholarships?q={q}"),
    ("DAAD Burs Veritabanı", "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/"),
    ("AcademicTransfer (Hollanda)", "https://www.academictransfer.com/en/jobs/?q={q}"),
]
